In [3]:
#Exercise 1: Create a numpy array and reshape it to a 2x5 matrix.


import numpy as np

arr = np.arange(1, 11)  # Create an array from 1 to 10
reshaped_arr = arr.reshape(2, 5)  # Reshape to 2x5 matrix
print(reshaped_arr)




[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [7]:
#Exercise 2: Extract elements between the 5th and 15th index from a numpy array.

arr = np.arange(1, 21)  # Create an array from 1 to 20
extracted_elements = arr[5:16]  # Extract elements from index 5 to 15
print(extracted_elements)


[ 6  7  8  9 10 11 12 13 14 15 16]


In [9]:
#Exercise 3: Create a Pandas series and add a new item.

import pandas as pd

fruit_series = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})  # Create series
fruit_series['pears'] = 4  # Add new item
print(fruit_series)


apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [11]:
#Exercise 4: Create a dataframe with name, age, and gender.
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Helen', 'Ian', 'Jack'],
    'age': [25, 30, 22, 45, 35, 28, 40, 32, 27, 50],
    'gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'M', 'M']
}

df = pd.DataFrame(data)
print(df)



      name  age gender
0    Alice   25      F
1      Bob   30      M
2  Charlie   22      M
3    David   45      M
4      Eve   35      F
5    Frank   28      M
6    Grace   40      F
7    Helen   32      F
8      Ian   27      M
9     Jack   50      M


In [13]:
#Exercise 5: Add a new column "occupation".
occupations = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 
               'Programmer', 'Manager', 'Analyst', 'Programmer']
df['occupation'] = occupations  # Add new column
print(df)



      name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   30      M     Manager
2  Charlie   22      M     Analyst
3    David   45      M  Programmer
4      Eve   35      F     Manager
5    Frank   28      M     Analyst
6    Grace   40      F  Programmer
7    Helen   32      F     Manager
8      Ian   27      M     Analyst
9     Jack   50      M  Programmer


In [ ]:
#Exercise 6: Select rows where the age is greater than or equal to 30.
python
Copy
Edit
